spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:web-store}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google.client-id: 1032723879805-m6plpl71f8b3esqnnpuc3cikik8470ij.apps.googleusercontent.com
          google.client-secret: aXUae1G-7E1JGWbbPJrgxlC0
server:
  port: 8081